### ISSUE TITLE
Sometimes the vibration does not stop.

### ISSUE THREAD

**Issue by zhangbo8418** [grayver/mi-vigem#2]
Just like mi-360,sometimes the vibration does not stop.

**Comment by grayver** [comment]
Hmm.. actually I'm experiencing the same in Super Lucky's Tale. I thought this is somehow connected with the game itself, but now I suspect that ViGEm is the problem. If you are experiencing same problem with mi-360 (which also uses ViGEm) then I'm almost sure that problem is somewhere in ViGEm. I'll try to communicate with ViGEm developers about this issue.

P.S. what game this issue is reproducible with?

**Comment by zhangbo8418** [comment]
The same in all games.

**Comment by zhangbo8418** [comment]
> Hmm.. actually I'm experiencing the same in Super Lucky's Tale. I thought this is somehow connected with the game itself, but now I suspect that ViGEm is the problem. If you are experiencing same problem with mi-360 (which also uses ViGEm) then I'm almost sure that problem is somewhere in ViGEm. I'll try to communicate with ViGEm developers about this issue.
> 
> P.S. what game this issue is reproducible with?


ViGEm has a new version, can you help compile it?

**Comment by grayver** [comment]
Could you try version 1.0.1 I've just released?

**Comment by zhangbo8418** [comment]
> Could you try version 1.0.1 I've just released?

No, the vibration will not stop. How to install ViGEmBus-1.17.258.0?

**Comment by grayver** [comment]
> No, the vibration will not stop. How to install ViGEmBus-1.17.258.0?

It seems to be they haven't published new installer yet. So you need to compile binaries from source code (and they will be unsigned, BTW).

But I think it wouldn't fix that problem. I talked to them yesterday and they said that problem either in client library, either in game itself. They confirmed, that problem existed in old client library which I used in release 1.0.0. Release 1.0.1 uses latest ViGEm client library.

I'm planning to add forced limitation for vibration time and this should help in that case.

**Comment by zhangbo8418** [comment]
As you said, there is indeed no solution. I compiled their new driver, but the problem remains（
I disabled signature detection.）.
https://github.com/irungentoo/Xiaomi_gamepad No problem, but occasionally it will disconnect, and then you need to restart the program.So it must be ViGEm's problem.

**Comment by grayver** [comment]
I've added limitation for constant long vibration in release 1.1.0 (2 sec). Can you try it out?

**Comment by zhangbo8418** [comment]
Okay, it can stop vibration.
